modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="legendary_ouba"
version="1.0.0"
displayName="Legendary OUBA"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[mixins]]
    config = "legendary_ouba.mixins.json"

# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.legendary_ouba]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.137,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.legendary_ouba]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration